insert into MEPages_celltissuetype value ( 1,'ES-EM5Sox17huCD25','ES-EM5Sox17huCD25','ES-EM5Sox17huCD25',0,NULL,'11',2 );
insert into MEPages_celltissuetype value ( 2,'EPC (CD117- CD71- TER119+)','EPC (CD117- CD71- TER119+)','EPC_(CD117-_CD71-_TER119+)',0,NULL,'3',2 );
insert into MEPages_celltissuetype value ( 3,'THelper-Activated','THelper-Activated','THelper-Activated',0,NULL,'10',2 );
insert into MEPages_celltissuetype value ( 4,'Headless Embryo','Headless Embryo','HeadlessEmbryo',0,NULL,'11',2 );
insert into MEPages_celltissuetype value ( 5,'FV-progenitor','FV-progenitor','FVprogenitor',0,NULL,'3',2 );
insert into MEPages_celltissuetype value ( 6,'Thymus','Thymus','Thymus',0,NULL,'10',2 );
insert into MEPages_celltissuetype value ( 7,'G1E','G1E','G1E',0,NULL,'3',2 );
insert into MEPages_celltissuetype value ( 8,'Liver','Liver','Liver',0,NULL,'6',2 );
insert into MEPages_celltissuetype value ( 9,'SpinalCord','SpinalCord','SpinalCord',0,NULL,'4',2 );
insert into MEPages_celltissuetype value ( 10,'ES-WW6_F1KO','ES-WW6_F1KO','ES-WW6_F1KO',0,NULL,'11',2 );
insert into MEPages_celltissuetype value ( 11,'ES-TT2','ES-TT2','ES-TT2',0,NULL,'11',2 );
insert into MEPages_celltissuetype value ( 12,'Lung','Lung','Lung',0,NULL,'5',2 );
insert into MEPages_celltissuetype value ( 13,'Brown Adipose Tissue','Brown Adipose Tissue','BAT',0,NULL,'8',2 );
insert into MEPages_celltissuetype value ( 14,'FVL-stem','FVL-stem','FVLstem',0,NULL,'3',2 );
insert into MEPages_celltissuetype value ( 15,'Fat Pad','Fat Pad','FatPad',0,NULL,'8',2 );
insert into MEPages_celltissuetype value ( 16,'TReg-Activated','TReg-Activated','TReg-Activated',0,NULL,'10',2 );
insert into MEPages_celltissuetype value ( 17,'EPC (CD117+ CD71+ TER119+)','EPC (CD117+ CD71+ TER119+)','EPC_(CD117+_CD71+_TER119+)',0,NULL,'3',2 );
insert into MEPages_celltissuetype value ( 18,'Hind Limb Bud','Hind Limb Bud','HindlimbBud',0,NULL,'1',2 );
insert into MEPages_celltissuetype value ( 19,'Bladder','Bladder','Bladder',0,NULL,'7',2 );
insert into MEPages_celltissuetype value ( 20,'L1210','L1210','L1210',0,NULL,'10',2 );
insert into MEPages_celltissuetype value ( 21,'Duodenum','Duodenum','Duodenum',0,NULL,'6',2 );
insert into MEPages_celltissuetype value ( 22,'Skeletal Muscle','Skeletal Muscle','SkMuscle',0,NULL,'2',2 );
insert into MEPages_celltissuetype value ( 23,'Skin','Skin','Skin',0,NULL,'7',2 );
insert into MEPages_celltissuetype value ( 24,'Testis','Testis','Testis',0,NULL,'9',2 );
insert into MEPages_celltissuetype value ( 25,'3134','3134','3134',0,NULL,'9',2 );
insert into MEPages_celltissuetype value ( 26,'Retina','Retina','Retina',0,NULL,'4',2 );
insert into MEPages_celltissuetype value ( 27,'T-Naive','T-Naive','T-Naive',0,NULL,'10',2 );
insert into MEPages_celltissuetype value ( 28,'ES-neurons','ES-neurons','ES-neurons',0,NULL,'4',2 );
insert into MEPages_celltissuetype value ( 29,'mG/ER','mG/ER','mG/ER',0,NULL,'10',2 );
insert into MEPages_celltissuetype value ( 30,'Patski','Patski','Patski',0,NULL,'7',2 );
insert into MEPages_celltissuetype value ( 31,'Pancreas','Pancreas','Pancreas',0,NULL,'8',2 );
insert into MEPages_celltissuetype value ( 32,'Cortex','Cortex','Cortex',0,NULL,'4',2 );
insert into MEPages_celltissuetype value ( 33,'Erythroblast','Erythroblast','Erythrobl',0,NULL,'3',2 );
insert into MEPages_celltissuetype value ( 34,'EpiSC-7','EpiSC-7','EpiSC-7',0,NULL,'11',2 );
insert into MEPages_celltissuetype value ( 35,'EpiSC-5','EpiSC-5','EpiSC-5',0,NULL,'11',2 );
insert into MEPages_celltissuetype value ( 36,'Fore Limb Bud','Fore Limb Bud','ForelimbBud',0,NULL,'1',2 );
insert into MEPages_celltissuetype value ( 37,'Limb','Limb','Limb',0,NULL,'1',2 );
insert into MEPages_celltissuetype value ( 38,'ZhBTc4','ZhBTc4','ZhBTc4',0,NULL,'11',2 );
insert into MEPages_celltissuetype value ( 39,'Placenta','Placenta','Placenta',0,NULL,'3',2 );
insert into MEPages_celltissuetype value ( 40,'416B','416B','416B',0,NULL,'10',2 );
insert into MEPages_celltissuetype value ( 41,'Ovary','Ovary','Ovary',0,NULL,'9',2 );
insert into MEPages_celltissuetype value ( 42,'ES-E14','ES-E14','ES-E14',0,NULL,'11',2 );
insert into MEPages_celltissuetype value ( 43,'Bone Marrow Derived Macrophage','Bone Marrow Derived Macrophage','BMDM',0,NULL,'10',2 );
insert into MEPages_celltissuetype value ( 44,'Whole Brain','Whole Brain','WholeBrain',0,NULL,'4',2 );
insert into MEPages_celltissuetype value ( 45,'ES-46C','ES-46C','ES-46C',0,NULL,'11',2 );
insert into MEPages_celltissuetype value ( 46,'Mesoderm','Mesoderm','Mesoderm',0,NULL,'11',2 );
insert into MEPages_celltissuetype value ( 47,'Adrenal','Adrenal','Adrenal',0,NULL,'8',2 );
insert into MEPages_celltissuetype value ( 48,'Stomach','Stomach','Stomach',0,NULL,'6',2 );
insert into MEPages_celltissuetype value ( 49,'EPC (CD117+ CD71+ TER119-)','EPC (CD117+ CD71+ TER119-)','EPC_(CD117+_CD71+_TER119-)',0,NULL,'3',2 );
insert into MEPages_celltissuetype value ( 50,'B-cell (CD43-)','B-cell (CD43-)','B-cell_(CD43-)',0,NULL,'10',2 );
insert into MEPages_celltissuetype value ( 51,'Olfactory Bulb','Olfactory Bulb','OlfactBulb',0,NULL,'4',2 );
insert into MEPages_celltissuetype value ( 52,'ES-WW6','ES-WW6','ES-WW6',0,NULL,'11',2 );
insert into MEPages_celltissuetype value ( 53,'J185a','J185a','J185a',0,NULL,'2',2 );
insert into MEPages_celltissuetype value ( 54,'A20','A20','A20',0,NULL,'10',2 );
insert into MEPages_celltissuetype value ( 55,'Frontal Lobe','Frontal Lobe','FrontalLobe',0,NULL,'4',2 );
insert into MEPages_celltissuetype value ( 56,'Spleen','Spleen','Spleen',0,NULL,'10',2 );
insert into MEPages_celltissuetype value ( 57,'Fibroblast','Fibroblast','Fibroblast',0,NULL,'5',2 );
insert into MEPages_celltissuetype value ( 58,'Cerebellum','Cerebellum','Cerebellum',0,NULL,'4',2 );
insert into MEPages_celltissuetype value ( 59,'Mammary Gland','Mammary Gland','MammaryGland',0,NULL,'9',2 );
insert into MEPages_celltissuetype value ( 60,'ES-CJ7','ES-CJ7','ES-CJ7',0,NULL,'11',2 );
insert into MEPages_celltissuetype value ( 61,'NIH-3T3','NIH-3T3','NIH-3T3',0,NULL,'10',2 );
insert into MEPages_celltissuetype value ( 62,'Heart','Heart','Heart',0,NULL,'3',2 );
insert into MEPages_celltissuetype value ( 63,'G1E-ER4','G1E-ER4','G1E-ER4',0,NULL,'3',2 );
insert into MEPages_celltissuetype value ( 64,'Large Intestine','Large Intestine','LgIntestine',0,NULL,'6',2 );
insert into MEPages_celltissuetype value ( 65,'EPC (CD117- CD71+ TER119+)','EPC (CD117- CD71+ TER119+)','EPC_(CD117-_CD71+_TER119+)',0,NULL,'3',2 );
insert into MEPages_celltissuetype value ( 66,'Bone Marrow','Bone Marrow','BoneMarrow',0,NULL,'10',2 );
insert into MEPages_celltissuetype value ( 67,'UpperLegMuscle','UpperLegMuscle','UpperLegMuscle',0,NULL,'2',2 );
insert into MEPages_celltissuetype value ( 68,'Megakaryocyte','Megakaryocyte','Megakaryo',0,NULL,'10',2 );
insert into MEPages_celltissuetype value ( 69,'EPC (CD117+ CD71- TER119-)','EPC (CD117+ CD71- TER119-)','EPC_(CD117+_CD71-_TER119-)',0,NULL,'3',2 );
insert into MEPages_celltissuetype value ( 70,'TReg','TReg','TReg',0,NULL,'10',2 );
insert into MEPages_celltissuetype value ( 71,'Kidney','Kidney','Kidney',0,NULL,'7',2 );
insert into MEPages_celltissuetype value ( 72,'Genital Fat Pad','Genital Fat Pad','GenitalFatPad',0,NULL,'8',2 );
insert into MEPages_celltissuetype value ( 73,'CH12','CH12','CH12',0,NULL,'10',2 );
insert into MEPages_celltissuetype value ( 74,'Subcutaneous Fat Pad','Subcutaneous Fat Pad','SubcFatPad',0,NULL,'8',2 );
insert into MEPages_celltissuetype value ( 75,'ES-Bruce4','ES-Bruce4','ES-Bruce4',0,NULL,'11',2 );
insert into MEPages_celltissuetype value ( 76,'C2C12','C2C12','C2C12',0,NULL,'2',2 );
insert into MEPages_celltissuetype value ( 77,'B-cell (CD19+)','B-cell (CD19+)','B-cell_(CD19+)',0,NULL,'10',2 );
insert into MEPages_celltissuetype value ( 78,'MEF','MEF','MEF',0,NULL,'11',2 );
insert into MEPages_celltissuetype value ( 79,'MEL','MEL','MEL',0,NULL,'10',2 );
insert into MEPages_celltissuetype value ( 80,'Small Intestine','Small Intestine','SmIntestine',0,NULL,'6',2 );
insert into MEPages_celltissuetype value ( 81,'MEP','MEP','MEP',0,NULL,'10',2 );
insert into MEPages_celltissuetype value ( 82,'ES-D3','ES-D3','ES-D3',0,NULL,'11',2 );
insert into MEPages_celltissuetype value ( 83,'10T1/2','10T1/2','10T1/2',0,NULL,'11',2 );
insert into MEPages_celltissuetype value ( 84,'Cerebrum','Cerebrum','Cerebrum',0,NULL,'4',2 );
insert into MEPages_celltissuetype value ( 85,'CNS','CNS','CNS',0,NULL,'4',2 );
insert into MEPages_celltissuetype value ( 86,'Colon','Colon','Colon',0,NULL,'6',2 );
